site_name: COMETS Documentation

extra_css:
    - css/extra.css

extra_javascript:
    - js/extra.js
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - mathjax-config.js

markdown_extensions:
    - toc:
        baselevel: 3
    - def_list
    - fenced_code
    - footnotes
    - admonition
    - pymdownx.arithmatex

nav:
        
    - Home: index.md
    - COMETS:
        - Capabilities: capabilities.md
        - Installation: installation.md
    - COMETS PYTHON TOOLBOX:
        - Getting started: getting_started.md
        - Growth in a test tube: test_tube.md
        - Competition assay: competition_assay.md
        - Citrate use in the LTEE: citrate.md
        - Circular colony growth: circular_colony.md
        - Branching colony growth: branching_colony.md
        - Demographic noise with two strains: demographic_noise_two_strains.md
        - Virtual Petri dish: petri_dish.md
    - COMETS MATLAB TOOLBOX:
        - Example: colony.md
theme: readthedocs
